### ISSUE TITLE
Does this work with Meteor 1.0?

### ISSUE THREAD

**Issue by zachheine** [spendflow/spendflow#5]

**Comment by wizonesolutions** [comment]
Hmm, it might; I haven't migrated packages on it, though. I would try it and file specific issues if you hit them.

**Comment by zachheine** [comment]
Pulled the repo and "meteor", get this error:

While building the application:
error: no such package: 'accounting'
error: no such package: 'i18n'
error: no such package: 'collection-hooks'
error: no such package: 'jquery-ui-bootstrap'
error: no such package: 'jquery-ui'
error: no such package: 'scss'
error: no such package: 'jquery-scrollintoview'
error: no such package: 'managedUsers'
error: no such package: 'moment'
error: no such package: 'analyticsjs'
error: no such package: 'canonical'
error: no such package: 'jquery-autosize'
error: no such package: 'iron-router'
error: no such package: 'font-awesome'
error: no such package: 'fast-render'

Then "meteor update" and get this error (sorry for the mess):

/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "U".
    at throwVersionParserError (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-version-parser.js:319:11)
    at Object.PV.validatePackageName (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-version-parser.js:306:5)
    at Object.PV.parseConstraint (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/package-version-parser.js:258:8)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/project.js:289:24
    at Function._.each._.forEach (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at _.extend.calculateCombinedConstraints (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/project.js:282:7)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1774:22
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:59:11
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:250:13
    at _.extend.withValue (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:243:29
    at _.extend.withValue (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:241:18
    at _.extend.withValue (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:232:23
    at _.extend.withValue (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:231:19)
    at exports.doOrDie (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:58:31)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1773:23
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:158:20
    at Array.some (native)
    at _.some._.any (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:207:59)
    at Function._.find._.detect (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:157:5)
    at maybeUpdateRelease (/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1768:34)
    at main.registerCommand.name [as func](/Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1899:29)
    at /Users/zrh0/.meteor/packages/meteor-tool/.1.0.36.umrkbq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1353:23

**Comment by wizonesolutions** [comment]
Yeah, packages aren't migrated, so you need to:

`npm install -g meteorite`

`mrt install`

as in `README.md`.

Try after that.
